name: Pages

on:
  push:
    branches:
      - master # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "22"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        working-directory: ./hexoblog
        run: npm install
      - name: Build
        working-directory: ./hexoblog
        run: npm run build
      # 指定 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # 执行 Python 脚本
      - name: Run Python Scripts
        working-directory: ./hexoblog
        run: |
          python compress.py
          python deploy.py
      # index.html
      - name: Prepare Deployment Structure
        run: |
          # 拷贝入口文件到根目录
          mkdir -p ./deploy_root
          cp ./index.html ./deploy_root/index.html
          cp ./404.html ./deploy_root/404.html
          # 拷贝资源文件到目录
          mkdir -p ./deploy_root/file
          cp -r ./file/* ./deploy_root/file/
          mkdir -p ./deploy_root/flash
          cp -r ./flash/* ./deploy_root/flash/
          mkdir -p ./deploy_root/fonts
          cp -r ./fonts/* ./deploy_root/fonts/
          mkdir -p ./deploy_root/images
          cp -r ./images/* ./deploy_root/images/
          mkdir -p ./deploy_root/video
          cp -r ./video/* ./deploy_root/video/
          # 拷贝 Hexo 生成的文件到 /blog
          mkdir -p ./deploy_root/blog
          cp -r ./blog/* ./deploy_root/blog/
      # 上传调整后的结构目录
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy_root
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4